[project]
name = "natalia"
version = "0.1.0"
description = "Add a short description here"
authors = ["Carlos Loucera <carlos.loucera@juntadeandalucia.es>"]
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pytorch-cuda = "12.1.*"
transformers = "4.29.*"
jupyterlab = ">=4.2.2,<4.3"
python = "3.10.*"
torchaudio = ">=2.3.1,<2.4"
torchvision = ">=0.18.1,<0.19"
pytorch = ">=2.3.1,<2.4"
einops = ">=0.8.0,<0.9"
monai = ">=1.3.1,<1.4"
numpy = ">=1.26.4,<1.27"
datasets = ">=2.19.2,<2.20"
matplotlib = ">=3.8.4,<3.9"

